### PR TITLE
feat: add an updated_at attribute to the meta attribute for the history API

### PR DESCRIPTION
**Pull request by emilesilvis**
For https://github.com/stevschmid/trackobot.com/issues/20.

### CODE REVIEW

**Comment by clooth** [comment]
I'm thinking this might be more efficient if we just make field in the user model be updated when one of its associations are updates (either the `result` or `deck` array).

What do you think?

**Comment by emilesilvis** [comment]
@clooth yup, `touch: true` will do it. I guess I need to wrap my head around the data models. So you're saying that we update `user.created_at` whenever the `result` or `deck` associations for that instance of `user` changes?

**Comment by emilesilvis** [comment]
@clooth would we also have to touch `user` when the `arena` association changes?

**Comment by clooth** [comment]
Hmm.. Well, `updated_at`, not `created_at`. I'm not sure. I'm primarily interested in knowing when I've had new matches. I guess decks at least sort of secondary. Was the `arena` association the arena matches or what?

**Comment by emilesilvis** [comment]
@clooth yes, it appears as if a `result` can belong to both a `user` (which I assume is casual or ranked) or `arena`.

**Comment by emilesilvis** [comment]
@clooth meant `updated_at`.

**Comment by clooth** [comment]
Now we just need tests and it's done, right? :+1:

**Comment by emilesilvis** [comment]
Current test suite is failing, so shouldn't that be fixed first?

**Comment by clooth** [comment]
I don't know, I haven't had any contributions so I haven't actively followed the development, you are right in that it probably should.

**Comment by emilesilvis** [comment]
@clooth I'll fix test suite in a different PR.

**Comment by emilesilvis** [comment]
Ok, test suite "fixed" in https://github.com/stevschmid/trackobot.com/pull/22.

**Comment by stevschmid** [comment]
Thanks for your work. There are a few issues though:

* What is the purpose of this PR? For #20, you can simply pull the first page of the history and look at the `added` attribute of the first result. 

* The PR contains a lot of noise. It seems for every new LOC there are 3 new gems which need to be installed. Every dependency hurts in the long run. 

* Touching the `user` when a `result` or `deck` changes? That messes with the intended data flow. The user is an isolated entity. I can understand touching in rare circumstances when an entity is spread out in different models, but that's not the case here.

**Comment by emilesilvis** [comment]
Those are all very good points, and thanks for taking the time to give detailed feedback. I guess I didn't understand the requirement or the data model that well. Here are some thoughts:

- That seems like a good solution (again, should've taken some more time to understand the data model).
- So I added only three gems, all of them development or test dependencies:
 - `pry-rails` is really an indispensable development tool, and I really don't think that it's adding any dependency.
 - `rails-erd` is really just a nice to have -- it generates an ERD of the data model. It's useful for someone that has no context of the data model and wants a quick overview. It can go, however.
 - `timecop` is just a testing dependency and is really useful when working with time. It can go, however (especially in light of the decision to follow an approach where we don't have to touch `user`).
- Yeah, this is probably a bit of a hack. Let's not touch `user`.

Let me work at this PR a bit more. Thanks again!

**Comment by stevschmid** [comment]
Thanks for your understanding! I will close this PR for now.

**Pull request closed without merging**
