### PR TITLE
Switch ranks over to individual, hi-res images

### LINKED ISSUE #60: Rank indicators in history are low-res
I am on my MacBook with Retina display, and I see sharp images for class indicators, but rank indicators are low-resolution in comparison:

screen shot 2016-06-23 at 12 41 24 am

The CSS for these images suggests that [there was some attempt of image swapping](https://github.com/stevschmid/trackobot.com/blob/dcfdf2b3bef88ce073aaab28ba5e98566b0df041/app/assets/stylesheets/ranks.scss#L188) for high-resolution displays, but the separate CSS rule simply loads the same (low-res) image again.

My suggestion would be that, due to the lack of high-res images for this, simple numbers as text could be used instead? I don't think it's really visually important that the rank indicators be identical to how they look in the game.

### PR DESCRIPTION
**Pull request by mislav**
The sprite approach was a premature optimization, as usually not many different rank images are going to be displayed on the same page at a time. Also, the sprite was very low-res and didn't look great on Retina.

This introduces individual, hi-res images for each rank. I've ran them through ImageAlpha and ImageOptim.

Fixes #60

### CODE REVIEW

**Comment by mislav** [comment]
Here's how it looks in action:

screen shot 2016-06-23 at 3 20 29 am

The resolution has greatly improved, but the images still don't look great. I think the problem is that they are partly transparent until you hover over individual rows. I don't think that effect is necessary. I'm going to propose simply having all row items at default opacity:

screen shot 2016-06-23 at 3 23 39 am

**Comment by stevschmid** [comment]
Thanks for the PR. Your version looks definitely better on my MBP. But on non-retina screens the downsampling leads to very blurry icons (tested in Chrome).  What do you think about serving two sizes of each icon (normal res/high res)?

**Comment by mislav** [comment]
> What do you think about serving two sizes of each icon (normal res/high res)?

That's not a bad idea, but I don't think it will make much of an impact. If we downsample these icons in an image editor and save them at tiny size for non-Retina displays, I think the result will still be blurry. These images simply weren't meant to be viewed at such small size.

How about dealing away with images altogether? Idea:

screen shot 2016-06-23 at 11 19 34 pm

Colors for different ranks are taken from those respective rank's edge of the seal.

**Comment by mislav** [comment]
Another idea: compromise:

screen shot 2016-06-23 at 11 35 30 pm

**Comment by stevschmid** [comment]
>  I think the result will still be blurry. These images simply weren't meant to be viewed at such small size.

The icons look great when viewed on a normal (non-retina) monitor. The downsampling makes them blurry though.

> Another idea: compromise:

I like the original icons since as a player you recognize them by heart. This strong association is lacking in your examples. I'm planning to create a new layout from scratch (without bootstrap) and I will definitely look on improving the display of the rank (going in the direction of your two last examples), but for now I would stick with serving two sizes.

**Comment by mislav** [comment]
Closing as it sounds from your last comment that you have a plan. 😉

**Pull request closed without merging**
