### PR TITLE
Changing deck match-quality from count to quotient

### PR DESCRIPTION
**Pull request by ganwell**
This is not meant to merge just yet. I think the formula is pretty decent, but I am not sure about the SQL.

Commit Message
-----------------------

When you define deck A with 4 cards and deck B with 10 cards
and result C will match A=4, B=5 cards then A is a better
match. Its a 100% match to A versus a 50% match to B.

Respecting this allows you to define some general
deck-categories and more specific decks. If the deck matches
a specific deck well, the specific will be selected,
otherwise it will fall back to a general deck.

Of course if less cards are played than defined in the
deck, the played cards count is used as divider. When the
quotient is the same, the deck with more cards (more
specific) wins:

cards_matching * 10000 / min(cards_deck, cards_played) + cards_deck

### CODE REVIEW

**Comment by stevschmid** [comment]
I have this week off so I can spend some time on Track-o-Bot. Is this PR still relevant @ganwell?

**Comment by emilesilvis** [comment]
This is an interesting PR, I'd like to help here. @ganwell I can help you with some tests.

Preliminary question from me: is there no way to just get the name given to a deck the game out of the logs? Then one can just match on name.

**Comment by stevschmid** [comment]
Thanks @emilesilvis. I don't think there is a way to get the deck name from the logs, plus it wouldn't help to detect the deck of your opponent.

I'm currently updating the website, including the deck recognition system. I suggest you hold off until I'm done with this (hopefully in the next couple of days)!

**Comment by emilesilvis** [comment]
Awesome @stevschmid, let us know if there's anything we can help with :smile:

**Comment by stevschmid** [comment]
Upcoming version will use a quotient-based deck recognition system. Thanks @ganwell for the idea! I was forced to redesign the storage of the card history data, which led to the removal of the views. So I couldn't make use of your PR.

**Pull request closed without merging**
