### PR TITLE
Adds Deck importing/exporting via text fields

### PR DESCRIPTION
**Pull request by JustinasDaugela**
- Allows the user to export all of his deck / import new ones via text forms

@stevschmid

### CODE REVIEW

**Comment by stevschmid** [comment]
Thanks. I will look into this as soon as I can!

**Comment by JustinasDaugela** [comment]
@stevschmid hey Steve, I'd love if you'd get a moment to review this. I'd be happy to import some decks myself and do some more work on the website.

**Comment by stevschmid** [comment]
Hey Justinas. Alas no time this week and next. But after that I'm gonna review the heck outta this PR. Thanks for your work!

**Comment by JustinasDaugela** [comment]
Ok, I'd love to colaborate more, especially since I'm playing quite a lot, so: )

**Comment by stevschmid** [comment]
I plan to revamp the whole deck system on the website. We'll see how well this feature plays along. I'm getting back to you once I know!

**Comment by JustinasDaugela** [comment]
Do you want any help in the revamping? I'd love to contribute

Regards,
Justinas

**Comment by stevschmid** [comment]
Hey Justinas! Thanks for the offer! I'm currently prototyping and have no concrete tasks, but maybe you could look at an issue which is already open? #29, #33 or #44 come in mind.

**Pull request closed without merging**
